# Generated by Django 4.2.5 on 2024-11-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Arduinos_serial'), (2, 'Arduinos_MQTT'), (3, 'Shellys')], default=1)),
                ('nombre', models.CharField(max_length=200)),
                ('puerto', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxred', models.IntegerField()),
                ('localIP', models.GenericIPAddressField()),
                ('broker_address', models.GenericIPAddressField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lcd', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inversores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Modos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('timeOn', models.CharField(max_length=200)),
                ('timeOff', models.CharField(max_length=200)),
                ('consumirExcedente', models.BooleanField(default=True)),
                ('tiempoAldia', models.IntegerField()),
                ('tiempoMaximo', models.IntegerField()),
                ('tiempoSeguido', models.IntegerField()),
                ('horaCorte', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'resistivo'), (2, 'capacitativo')], default=1)),
                ('nombre', models.CharField(max_length=200)),
                ('power', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('pinPower', models.IntegerField()),
                ('minPower', models.IntegerField()),
                ('tiempo_reaccion', models.IntegerField()),
                ('modoDia', models.CharField(max_length=200)),
                ('ardu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excedentes.actuadores')),
            ],
        ),
    ]
