# Generated by Django 4.2.5 on 2024-11-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excedentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instalacion',
            new_name='Instalaciones',
        ),
    ]
