# Generated by Django 4.2.5 on 2024-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excedentes', '0002_rename_instalacion_instalaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='modos',
            name='dispositivos',
            field=models.ManyToManyField(to='excedentes.dispositivos'),
        ),
    ]
