# Generated by Django 4.2.5 on 2024-11-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excedentes', '0006_alter_modos_timeoff_alter_modos_timeon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivos',
            name='modoDia',
        ),
        migrations.RemoveField(
            model_name='modos',
            name='dispositivos',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoDomingo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='domingo', to='excedentes.modos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoJueves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jueves', to='excedentes.modos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoLunes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lunes', to='excedentes.modos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoMartes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='martes', to='excedentes.modos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoMiercoles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='miercoles', to='excedentes.modos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoSabado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sabado', to='excedentes.modos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modoViernes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='viernes', to='excedentes.modos'),
        ),
    ]
