# Generated by Django 4.2.5 on 2024-11-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excedentes', '0008_alter_dispositivos_tiempo_reaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modos',
            name='timeOff',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='modos',
            name='timeOn',
            field=models.JSONField(default=[]),
        ),
    ]
