# Generated by Django 4.2.5 on 2024-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excedentes', '0012_alter_modos_timeoff_alter_modos_timeon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modos',
            name='horaCorte',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='modos',
            name='timeOff',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='modos',
            name='timeOn',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
